package tl:guy-fighter;

interface host {
    record type-of-guy {
        name: string,
        strength: u8,
        charisma: u8,
        agility: u8,
        battle-cries: list<string>,
    }
    invent-entirely-new-type-of-guy: func(guy-type: type-of-guy);
}

world plugin {
    import host;
    export init: func();
    export get-plugin-name: func() -> string;
}



